version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed for this static website."
  build:
    commands:
      - echo "Building the static website..."
  post_build:
    commands:
      - echo "Deploying to S3 bucket..."
      - aws s3 sync ./ s3://<your-bucket-name> --delete
artifacts:
  files:
    - '**/*'
